### ISSUE TITLE
infografía, Jordán Mendoza Aparicio 

### ISSUE THREAD

**Issue by JORDAN880768** [SistemasTecTlaxiaco/infografia-JORDAN880768#1]
[infografía, Jordan.pdf](https://github.com/user-attachments/files/16741727/infografia.Jordan.pdf)

**Comment by mae18-25** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:14/14
Referencias:14/14
Presentación:14/14
Calificación Final: 19.8

**Comment by josealfredo79** [comment]
bien hecho y revisado..
